Genymobile/genymotion-device-web-player

README.md
Add missing documentation regarding player disconnection.
Fixes #<issue>
=> Missing documentation around player disconnection

README.md, bower.json, package.json
=> Bump to version 1.4.4

README.md
Fix wrong URLs to Genymotion Device image documentation.
Fixes #10
=> Fix bad URL (404) in README.md

README.md, bower.json, package.json
=> Bump to version 2.0.3

src/GenymotionInstance.js, src/plugins/Network.js, tests/unit/network.test.js
Fix Network throttling widget on devices that do not report mobileThrottling capability.
Fixes #SYSTEM-1911
=> Fix network throttling regressions

src/GenymotionInstance.js
Baseband and Phone widgets depend on the same capability.
Fixes GOD-2434
=> [GOD-2434] Fix baseband widget

README.md
Now point to : https://docs.genymotion.com/paas/01_Requirements/
=> Fix PaaS documentation link.

src/DeviceRenderer.js
Regex matching was incorrect, and 'stereo=1' was not munged into the SDP. Tested under Chrome, Firefox & Safari
=> fix: stereo sound support for Chrome & Safari

README.md, bower.json, package.json
=> Bump to version 3.0.2

README.md, bower.json, package.json, src/DeviceRenderer.js, tests/unit/camera.test.js
=> Bump version to 3.0.3

README.md, bower.json, package.json
Please include a summary of the change and which issue is fixed if any. Please also include relevant motivation and context (a screenshot is appreciated).
Fixes #<issue>
=> Bump to version 3.0.4

src/DeviceRenderer.js, src/plugins/BasebandRIL.js, src/plugins/Fullscreen.js, src/plugins/GPS.js, src/plugins/Gamepad.js, src/plugins/GamepadManager.js, src/plugins/Identifiers.js, src/plugins/KeyboardEvents.js, src/plugins/MediaManager.js, src/plugins/MouseEvents.js, src/plugins/MultiTouchEvents.js, src/plugins/Phone.js
This PR introduces a mechanism of centralized handlers. This allows all of the handlers to be cleanely removed at destruction time, and for the device renderer to be fully picked up by the garbage collector.
=> Centralized handlers

src/DeviceRenderer.js, src/DeviceRendererFactory.js, src/plugins/Camera.js
This branch fix 2 bug on V3 player
- issue with the order on which plugin are called
- Camera plugin doesn't works
plus a little change on name of the fingerprint capabitilies (fingerprint => biometrics)
=> [GOD-2505] fingerprint feature fix bug

tests/mocks/DeviceRenderer.js, tests/unit/fingerprint.test.js
fix fingerprint TU failed cause store wasn't mocked
=> fix fingerprint TU by adding a mock for the store

README.md, bower.json, package.json
bump version v3.1.0 to v3.2.0 with some bug fix and fingerprint support
=> Bump to version 3.2.0

src/DeviceRenderer.js, src/plugins/KeyboardEvents.js
=> [Integration] [PLAYER-7] fix issue when destroy a not fully initialized player

src/DeviceRenderer.js, src/plugins/KeyboardEvents.js
for release 3.2.1 with bug fix 
- https://genymobile.atlassian.net/browse/PLAYER-1
- https://genymobile.atlassian.net/browse/PLAYER-7
=> [DONT MERGE] Epic for realease 3.2.1 player 7 player 1

README.md, bower.json, package.json
=> [Bump] to version 3.2.1

src/DeviceRendererFactory.js
change option name fingerprint by biometrics
=> change option fingerprint's name by biometrics, in accordance with readme

README.md, bower.json, package.json
=> Bump to version 3.2.2

README.md, src/DeviceRenderer.js, src/DeviceRendererFactory.js
=> Manage gamepad capability

README.md, gulpfile.js
Change name of exposed variable that gulp attach to window object
Fixes #<issue>
=> change name of object attached to window

README.md, bower.json, package.json
=> Bump to version 4.0.0

README.md, bower.json, package.json
=> Bump to version 4.0.1

src/plugins/FileUpload.js
fix amplitude gapps_installed events send each time a VM with gapps alredy installed is started
=> send gapps only after installation

README.md, bower.json, package.json
=> Bump to version 4.1.0

example/geny-window.css, example/geny-window.html, example/geny-window.js
Adding setting to example : 
- Save token
- Save instance history
- Change baseurl
=> adding advanced settings

README.md, bower.json, package.json
=> Bump to version 4.1.2

example/geny-window.html, gulpfile.js, package.json, yarn.lock
Adding version to minified files
-   [x] New feature (non-breaking change which adds functionality)
=> [PLAYER-39] adding player version to js and css minified files

README.md, bower.json, example/geny-window.html, package.json
=> Bump to version 4.1.4

README.md
added 'SAAS' to baseband compatiblity section of the README file
=> [SAAS-5359] added SAAS to baseband compatitlity Reamde file

src/plugins/Clipboard.js, src/plugins/Phone.js, src/plugins/util/OverlayPlugin.js, src/plugins/util/components.js, src/scss/components/_clipboard.scss, src/scss/components/_phone.scss, src/scss/components/_textArea.scss, src/scss/components/_textInput.scss, src/scss/components/_widgetwindow.scss, src/scss/main.scss, tests/unit/phone.test.js
rework ui of sms and call widget
=> [PLAYER-50] rework ui of sms and call widget

.github/workflows/integration.yml, .github/workflows/release.yml, package.json
- update node engine for project to V20 (V16 deprecated)
- update github `@actions` v2 (deprecated) to V4
Fixes #<issue>
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] I've read & comply with the [contributing guidelines](https://github.com/Genymobile/genymotion-device-web-player/blob/main/CONTRIBUTING.md)
-   [ ] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
-   [ ] I have made corresponding changes to the documentation (README.md).
-   [ ] I've checked my modifications for any breaking changes.
=> Update node v20 and actions GitHub v4

src/plugins/GPS.js, src/scss/components/_gps.scss
- better manage of disble 'set my position' btn when location permission denied
- fix css label on gmaps
-  placeholder when gmaps are not loaded
=> [PLAYER-58] refacto gps handle qa comments

src/plugins/IOThrottling.js, src/scss/components/_iothrottling.scss
error message on custom value field for iothrottling plugin
=> [PLAYER-66] Disk I/O min and max values for Custom profile

README.md, bower.json, package.json
=> Bump to version 4.2.1
