Genymobile/genymotion-device-web-player

CONTRIBUTING.md
README.md
package.json
src/plugins/GPS.js
tests/unit/gps.test.js

When using the GPS widget, an error pops up in the console is google maps library is missing
**Console error:** 
**Adapted UI (maps button disabled)** 
Things done: 
- Document the requirement
- Remove error logging, make the UI detect if the requirement is met
- Update contribution documentation
Fixes #<issue>

Avoid logging an error for visual positioning missing library.

---

README.md

Disable `fileUpload` widget in readme exemple to avoid missing `fileUploadUrl` configuration error.
As already documented, the `fileUpload` option (enabled by default) requires another option to be set: `fileUploadUrl`. Otherwise, this happens:

Disable fileupload to avoid missing configuration error.

---

README.md

The code sample was incomplete because of the variable "container" not being defined. This commit add the missing declaration and fixes the issue.
| Before  | After |
| :-------: |:------:|
| ![image](https://user-images.githubusercontent.com/1827605/188891915-de4b43c9-5f30-4e00-8e80-0d509647d9f1.png)  | ![image](https://user-images.githubusercontent.com/1827605/188891947-9adc76f3-9914-4a93-9acf-f65b047a5503.png)

Fix missing "container" variable declaration

---

src/plugins/Network.js

This is due to the fact redis messages are received after reboot while the widget is already created and did not rendered from scratch To avoid such behaviour we add 2 boolean variable to check if the mobile throttling ans 5G enabling/disabling operation was already done or not.
Please include a summary of the change and which issue is fixed if any. Please also include relevant motivation and context (a screenshot is appreciated).
Fixes #<issue>

Fix network widget elements duplicated

---

src/plugins/Clipboard.js
tests/unit/clipboard.test.js

Let's simplify the copy/paste widget and avoid non solicited Host clipboard modification.
This will just represent the device clipboard and user will just copy/paste onto it or modify it freely.
We might rework the widget later, but this will help users understand its mechanism.

Rework copy/paste widget

---

src/DeviceRenderer.js

Update unmute popup:
- ~~make it clickable too (since the cursor suggests this anyway)~~ in fact, make the whole window clickable
- add i18n for this popup
This could probably be merged in the main branch too.

Fix unmute popup

---

src/DeviceRenderer.js
src/plugins/MediaManager.js
tests/unit/camera.test.js

This PR adds return values to most functions in media manager in order to communicate with users of this class if we failed to initialise video or audio input.

Media manager: Add return values in order to fail loudly

---

src/DeviceRenderer.js

Following a suggestion from @jparez , this small PR simplifies the detecting when a click outside the overlay is done.

Simplify click outside overlay detection

---

src/DeviceRenderer.js
src/plugins/GamepadManager.js
src/plugins/KeyboardEvents.js
src/plugins/MediaManager.js
src/plugins/MouseEvents.js
src/plugins/PeerConnectionStats.js

This PR improves Device Renderer destruction, in hopes of it getting garbage-collected when we don't need it anymore.
Most event handlers lambda were moved to class methods, so that they could be properly removed, and most plugins had `destroy` functions added, and called in the Device Renderer `destroy`.

Improve Device Renderer destruction

---

src/plugins/KeyboardEvents.js

Fix bug when typing charater outside of player events were send to the instance

[PLAYER-2] bind keypress envent on root div instead of window object

---

src/DeviceRenderer.js

When calling setupRender and destroy() in a loop destroy() destroy try to delete object not already load
see https://genymobile.atlassian.net/browse/PLAYER-7

[PLAYER-7] fix issue when destroy a not fully initialized player

---

src/plugins/KeyboardEvents.js

[Integration] [PLAYER-1] fix issue with kepress bind on window

---

src/plugins/Gamepad.js
src/plugins/GamepadManager.js

Rework Gamepad and Gamepad Management to fix:
- handle gamepad pugged/unplugged
- catch and handle confirmation
- send correct vinput gamepad redis message
- Handle axis changes
- Rework catch and dispatch event to dispatch it only when axes changed
- Add vendor id and product id to the plugg in command

System 2449/fix gamepad

---

gulpfile.js
src/DeviceRenderer.js
src/plugins/Gamepad.js
src/plugins/GamepadManager.js

- cleanup logerror for gamepadmanager
- adding an option to preserve class and fn's name when file are uglify in prod mode. In order to have class.name works when file is uglify (cause name's class are replace by shorter name), see #72 at plugin.class.name
Jira issue: https://genymobile.atlassian.net/browse/PLAYER-8
- #73 
- #72

cleanup logerror for gamepadmanager

---

README.md
src/APIManager.js
src/DeviceRendererFactory.js
src/plugins/MediaManager.js
src/plugins/MouseEvents.js
tests/mocks/DeviceRenderer.js

Add an `APIManager` to expose the player API.
This is a breaking change since `setupRendere`r now returns the API, not the `DeviceRendererFactory` object.

[PLAYER-18] api manager

---

.eslintrc.json
gulp/graspify-squery.js
src/DeviceRenderer.js
src/plugins/BasebandRIL.js
src/plugins/Battery.js
src/plugins/Clipboard.js
src/plugins/FileUpload.js
src/plugins/FingerPrint.js
src/plugins/GPS.js
src/plugins/Gamepad.js
src/plugins/IOThrottling.js
src/plugins/Identifiers.js
src/plugins/KeyboardEvents.js
src/plugins/MouseEvents.js
src/plugins/Network.js
src/plugins/Phone.js
src/plugins/Screencast.js
src/plugins/util/OverlayPlugin.js
src/store/index.js
src/utils/helpers.js
src/worker/FileUploaderWorker.js
tests/mocks/DeviceRenderer.js
tests/unit/clipboard.test.js
tests/unit/fileupload.test.js

PR before adding keymapping plugin. The goal is to have a cleaner way to manage the keyboard status.
- Overlay have been refacto to be manage by store
- Keyboard key press enable / disable have been refacto to be manage by store
- some eslint on a separate commit

[PLAYER-19] pre-keybinding refacto keyboard enable/disable and overlay

---

src/plugins/FileUpload.js
src/plugins/GamepadManager.js
src/plugins/KeyboardEvents.js
src/plugins/KeyboardMapping.js
src/plugins/MouseEvents.js
src/plugins/util/OverlayPlugin.js
src/store/index.js
tests/unit/apiManager.test.js

Refacto store to subscribe only part of store change. Most likely React useEffect hook, we can now supply an array of dependencies. If no array is supply then the callback will be trigger on each store change
**this callback will be trigger only on isKeyboardEventsEnabled change**
```
this.instance.store.subscribe(
({isKeyboardEventsEnabled}) => {
...
},
['isKeyboardEventsEnabled'],
);
```
**nested object**
```
this.instance.store.subscribe(
({isKeyboardEventsEnabled}) => {
...
},
['overlay.widgetOpened'],
);
```
**Trigger on all change**
```
this.instance.store.subscribe(
({isKeyboardEventsEnabled}) => {
...
}
);
```
Adding functions to ApiManager to track events
Events currently tracked
- opengapps installed
- gamepad plug / unplug
- widget opened / closed
-   [x] New feature …

[PLAYER-25] adding api to track event

---

src/APIManager.js
src/DeviceRenderer.js
src/plugins/GamepadManager.js

This PR have several fix
- replace exposed API addEventlistener by the dedicated registerEventCallback function
- added closure on this.video for onConnectionClosed function? This way if we connect the VD more than 1 time this.video isn't undefined anymore
- remove gamepad unplug tracked event

[PLAYER-35] change add event listener in apimanager

---

src/plugins/KeyboardMapping.js

When a css rules (i.e. scale) is set on the player's HTML element the calculation of borders is wrong. This is caused by the offset's browser api which doesn't take css rules in this calculation
- change way of borders are calculated
- fix bug on keymapping debug grids for portrait

[PLAYER-31] fix wrong calculation border with css scale rule

---

src/plugins/MouseEvents.js

fix bug when clicking on the icon of the resolution plugin, the selectbox wasn't displayed
Element of the listener wasn't correct

[PLAYER-38] change HTML  parent element of mouseevent listener plugin

---

README.md
index.d.ts
src/plugins/KeyboardMapping.js

replace the key named keys to 'key' for tap and swipe in the json config
update json keymapping config.
```
TYPE:[{
keys: {
p: {
initialX: 50,
initialY: 50,
},
}
name:'Fire'
}],
```
to
```
dPad:[{
keys: {
key: 'p',
effect: {
initialX: 50,
initialY: 50,
},
}
name:'Fire'
}],
tap:[{
key: 'p',
effect: {
initialX: 50,
initialY: 50,
},
name:'Fire'
}],
```

[PLAYER-30] remplace the key 'keys' to 'key' for keympapping tap et swipe

---

src/DeviceRendererFactory.js

When player is used in third party app class.name could be empty in case of uglify process on node modules
-   [x] Bug fix (non-breaking change which fixes an issue)

replace way of check if plugin charged

---

src/plugins/BasebandRIL.js
src/plugins/Battery.js
src/plugins/Camera.js
src/plugins/Clipboard.js
src/plugins/FileUpload.js
src/plugins/FingerPrint.js
src/plugins/Fullscreen.js
src/plugins/GPS.js
src/plugins/Gamepad.js
src/plugins/IOThrottling.js
src/plugins/Identifiers.js
src/plugins/KeyboardEvents.js
src/plugins/KeyboardMapping.js
src/plugins/MouseEvents.js
src/plugins/MultiTouchEvents.js
src/plugins/Network.js
src/plugins/Phone.js
src/plugins/Screencast.js
src/plugins/StreamBitrate.js
src/plugins/StreamResolution.js

adding static get name() to plugins class, in order to be able to use this.constructor.name in third app which uglify this script
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

adding static get name on the plugins class

---

README.md
index.d.ts
src/DeviceRenderer.js
src/DeviceRendererFactory.js
src/plugins/ButtonsEvents.js
tests/unit/buttonsevent.test.js

**JIRA**: [SYSTEM-2682 ](https://genymobile.atlassian.net/browse/SYSTEM-2682)
Home widget button is broken on ARM SaaS which uses a PaaS image, as desktop & paas images handle the home button differently. 
First, the [Android documentation](https://source.android.com/docs/core/interaction/input/keyboard-devices#hid-keyboard-and-keypad-page-0x07) for the actual mapping between linux keyboard keycodes and Android keycodes tells us:
- Linux `KEY_HOMEPAGE` (`Qt::Key_HomePage`) maps to Android [KEYCODE_HOME](https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_HOME) and is the physical home button (back to "desktop")
- Linux `KEY_HOME` (`Qt::Key_Home`) maps to Android [KEYCODE_MOVE_HOME](https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_MOVE_HOME) and is 
> …

Always translate home into meta+enter

---

example/geny-window.html
example/geny-window.js

~☝🏻 This is currently based on top of #112. It should be rebased on `main` after #112 is merged.~
See the documentation for `POST /v1/instances/access-token`: https://developer.genymotion.com/saas/#tag/Instances-v1/operation/accessToken
It has an `instance_uuid` request payload field.
Now that an instance uuid is required to connect to a SaaS instance, clarify that:
* Connection via instance uuid is only for Genymotion SaaS.
* Connection via webrtc address is only for Genymotion Device Image.
Tested accessing a device:
|Platform|By launching from the example|By connecting to already launched device|
|---|---|---|
|SaaS|![image](https://github.com/user-attachments/assets/337d8371-053d-494e-89af-c555917463d0)|![image](https://github.com/user-attachments/assets/ab2aa2ad-d195-4c76-978f-b5569bc …

Update the example to use the latest apis for fetching recipes and accessing instances.

---

src/assets/images/ic_check.svg
src/assets/images/ic_close-modal.svg
src/assets/images/ic_close.svg
src/plugins/Battery.js
src/plugins/IOThrottling.js
src/plugins/util/components.js
src/plugins/util/iothrottling-profiles.js
src/scss/base/_animations.scss
src/scss/base/_genymotion.scss
src/scss/base/_variables.scss
src/scss/components/_battery.scss
src/scss/components/_chipTag.scss
src/scss/components/_dropdown.scss
src/scss/components/_iothrottling.scss
src/scss/components/_textInput.scss
src/scss/components/_toolbar.scss
src/scss/components/_widgetwindow.scss
src/scss/main.scss
tests/unit/iothrottling.test.js

- adding readonly and fix bug on regexFilter. Refacto swicth setState
- dropdown and chipTag components
-  Rework ioThrottling plugin UI / UX in accordance to figma

[PLAYER-49] refacto disk io

---

src/plugins/GPS.js
src/plugins/util/components.js
src/scss/components/_dropdown.scss

- Fix the position of the sliders at start
- Fix altitude in GPS plugin, which was being auto-set whenever latitude or longitude changed 
- reduce the size of dorpdow items to be compliant with figma
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

[PLAYER-87][PLAYER-86] fix issue post 4.2.0 (altitude autoset and slider component position at start)
